name: kikilt
description: 一个少女风格的跨平台文件传输应用
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # LocalSend 共享模块库
  # 方案1: 直接将common库集成到项目中
  common:
    path: lib/common

  # 方案2: 如果确实需要使用packages文件夹，确保创建此目录
  # common:
  #   path: packages/common

  # 状态管理
  refena: ^2.0.0
  refena_flutter: ^2.0.0

  # 路由
  go_router: ^12.1.1

  # UI组件
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  confetti: ^0.7.0

  # 文件处理
  file_picker: ^6.1.1
  file_selector: ^1.0.1
  path_provider: ^2.1.1
  open_filex: ^4.3.4
  path: ^1.8.3
  mime: ^1.0.4

  # 存储
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0

  # 工具
  intl: ^0.18.1
  logger: ^2.0.2
  uuid: ^4.2.1
  flutter_svg_provider: ^1.0.6
  collection: ^1.17.2
  url_launcher: ^6.2.1
  flutter_animate: ^4.3.0
  dart_mappable: ^4.2.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  dart_mappable_builder: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: KikiIcons
      fonts:
        - asset: assets/fonts/KikiIcons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"